spring.application.name=Video-Streaming-App

# Set active profile
spring.profiles.active=prod
spring.threads.virtual.enabled=true
server.port=${PORT:8080}

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${OAUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=${APP_BASE_URL:http://localhost:8080}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email,profile,openid

# Application Settings
app.api.base-url=${APP_BASE_URL:http://localhost:8080}
app.auth.success-redirect=https://video-streaming-app-lac.vercel.app/login
app.auth.failure-redirect=https://video-streaming-app-lac.vercel.app/login?error=oauth_failed

# CloudFlare R2 Configuration
cloudflare.r2.access-key=${CLOUDFLARE_R2_ACCESS_KEY}
cloudflare.r2.secret-key=${CLOUDFLARE_R2_SECRET_KEY}
cloudflare.r2.bucket-name=${CLOUDFLARE_R2_BUCKET_NAME}
cloudflare.r2.endpoint=${CLOUDFLARE_R2_ENDPOINT}
cloudflare.r2.public-url=${CLOUDFLARE_R2_PUBLIC_URL}

# JWT Configuration
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration-ms=1296000000

# OTP Configuration
app.otp.expiration-ms=300000
app.otp.length=6
ott.token.expiry.seconds=300

# Twilio Configuration
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}

# Mail Configuration
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.from=SnapBuy <${EMAIL_USERNAME}>
spring.mail.port=587
spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger / OpenAPI Configuration
springdoc.api-docs.version=OPENAPI_3_0
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# HikariCP Configuration
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.validation-timeout=2000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.max-lifetime=600000
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=15s

# Logging configuration (common across all profiles)
spring.output.ansi.enabled=always
logging.level.root.com.CodeWithRishu.Video_Streaming_App=DEBUG
management.endpoints.web.exposure.include=health
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level){yellow} %clr([%15.15t]){cyan} %clr(%-40.40logger{39}){blue} : %m%n