# MySQL connection - use environment variables
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File upload settings
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

file.upload-dir=/tmp/uploads
file.video.hsl-dir=/tmp/videos_hsl

server.port=${PORT:8080}

spring.output.ansi.enabled=always
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level){yellow} %clr([%15.15t]){cyan} %clr(%-40.40logger{39}){blue} : %m%n