spring.application.name=Video-Streaming-App

# Set active profile
spring.profiles.active=dev

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${OAUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email,profile,openid

# Application Settings
app.api.base-url=${APP_BASE_URL:http://localhost:8080}
app.auth.success-redirect=http://localhost:5173/login
app.auth.failure-redirect=http://localhost:5173/login?error=oauth_failed
server.port=8080

# JWT Configuration
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration-ms=1296000000

# OTP Configuration
app.otp.expiration-ms=300000
app.otp.length=6
ott.token.expiry.seconds=300

# Twilio Configuration
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}

# Mail Configuration
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.from=SnapBuy <${EMAIL_USERNAME}>
spring.mail.port=587
spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.root.com.CodeWithRishu.SnapBuy=DEBUG

# Swagger / OpenAPI Configuration
springdoc.api-docs.version=OPENAPI_3_0
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
spring.mvc.throw-exception-if-no-handler-found=false
spring.web.resources.add-mappings=true

# Logging configuration (common across all profiles)
spring.output.ansi.enabled=always
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level){yellow} %clr([%15.15t]){cyan} %clr(%-40.40logger{39}){blue} : %m%n