spring.application.name=Video-Streaming-App

# Set active profile
spring.profiles.active=dev

logging.level.com.CodeWithRishu.Video_Streaming_App=DEBUG
logging.level.root=INFO

# Logging configuration (common across all profiles)
spring.output.ansi.enabled=always
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level){yellow} %clr([%15.15t]){cyan} %clr(%-40.40logger{39}){blue} : %m%n