spring.application.name=Video-Streaming-App

# Set active profile
spring.profiles.active=dev

jwt.secret=${JWT_SECRET_KEY}

spring.mail.username=rg2822046@gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.from=SnapBuy <rg2822046@gmail.com>
spring.mail.port=587
spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.api-docs.version=OPENAPI_3_0
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

app.base-url=http://localhost:8080
ott.token.expiry.seconds=300

# Logging configuration (common across all profiles)
spring.output.ansi.enabled=always
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level){yellow} %clr([%15.15t]){cyan} %clr(%-40.40logger{39}){blue} : %m%n